language: python
notifications:
  email: false
python:
  - "3.6"
os:
  - linux
addons:
  apt:
    packages:
      - gfortran
install:
  - cd ./tests
  - ./travis_build_siteid.sh
  - cd ..
script:
  - cd ./tests
  - python -m unittest discover

